//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rental.Model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentalEntities : DbContext
    {
        public RentalEntities()
            : base("name=RentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Slider> Slider { get; set; }
        public DbSet<Area> Area { get; set; }
        public DbSet<Room> Room { get; set; }
        public DbSet<RoomImageInfo> RoomImageInfo { get; set; }
        public DbSet<Service> Service { get; set; }
        public DbSet<ServiceImageInfo> ServiceImageInfo { get; set; }
        public DbSet<Food> Food { get; set; }
        public DbSet<FoodImageInfo> FoodImageInfo { get; set; }
    }
}
