//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rental.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rental.UI.Resources.zh-CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 配套设施 的本地化字符串。
        /// </summary>
        public static string AncillaryFacility {
            get {
                return ResourceManager.GetString("AncillaryFacility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到达指引 的本地化字符串。
        /// </summary>
        public static string Arrival {
            get {
                return ResourceManager.GetString("Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本信息 的本地化字符串。
        /// </summary>
        public static string BasicInfo {
            get {
                return ResourceManager.GetString("BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品味美食 的本地化字符串。
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到达指引 的本地化字符串。
        /// </summary>
        public static string Guidance {
            get {
                return ResourceManager.GetString("Guidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 酒店介绍 的本地化字符串。
        /// </summary>
        public static string HotelProfile {
            get {
                return ResourceManager.GetString("HotelProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string IndexPageName {
            get {
                return ResourceManager.GetString("IndexPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间信息 的本地化字符串。
        /// </summary>
        public static string IndexRoomName {
            get {
                return ResourceManager.GetString("IndexRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对不起，暂无信息 的本地化字符串。
        /// </summary>
        public static string NoResource {
            get {
                return ResourceManager.GetString("NoResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优惠精选 的本地化字符串。
        /// </summary>
        public static string Preference {
            get {
                return ResourceManager.GetString("Preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 精选优惠 的本地化字符串。
        /// </summary>
        public static string PreferenceSelection {
            get {
                return ResourceManager.GetString("PreferenceSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间 的本地化字符串。
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间预览 的本地化字符串。
        /// </summary>
        public static string RoomPrivew {
            get {
                return ResourceManager.GetString("RoomPrivew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务设施 的本地化字符串。
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 台湾 的本地化字符串。
        /// </summary>
        public static string TaiWan {
            get {
                return ResourceManager.GetString("TaiWan", resourceCulture);
            }
        }
    }
}
